### PR TITLE
added ignoring of CommandNotFound error

### PR DESCRIPTION
**Pull request by quinnabrvau**
@JimLiu0 you should double check this but I believe it will suppress the error messages that are clogging up the logs

also removed 1 duplicate function to an alias for clean up, because I couldn't help myself

### CODE REVIEW

**Comment by JimLiu0** [comment]
It did not appear to work, I'm still getting the CommandNotFound error logged to STDERR

File: src/twitch.py [hunk 1]
```diff
@@ -142,14 +145,17 @@ async def bgdailii(ctx):
...
-@twitchBot.command(name='help')
+@twitchBot.command(name='help', aliases=['wall_lii'])
 async def help(ctx):
     await ctx.send('HeyGuys I\'m a bot that checks the BG leaderboard to get data about player ranks and daily MMR fluctuations. I reset daily at Midnight CA time. Try using !bgrank [name] and !bgdaily [name] and !yesterday [name]. Also try !buddy [hero] and !goldenbuddy [hero] for buddy info')
 
+@twitchBot.event()
+async def event_error(error, data):
+    if isinstance(error, CommandNotFound):
+        return
+    traceback.print_exception( type(error), error, error.__traceback__, file=sys.stderr)
```
Comment (BoraxTheClean) [inline src/twitch.py:156]: Is this intention here to print the exception instead of raising the exception?

File: src/twitch.py [hunk 2]
```diff
@@ -142,14 +145,17 @@ async def bgdailii(ctx):
...
-
-@twitchBot.command(name='help')
+@twitchBot.command(name='help', aliases=['wall_lii'])
 async def help(ctx):
     await ctx.send('HeyGuys I\'m a bot that checks the BG leaderboard to get data about player ranks and daily MMR fluctuations. I reset daily at Midnight CA time. Try using !bgrank [name] and !bgdaily [name] and !yesterday [name]. Also try !buddy [hero] and !goldenbuddy [hero] for buddy info')
 
+@twitchBot.event()
+async def event_error(error, data):
+    if isinstance(error, CommandNotFound):
+        return
```
Comment (BoraxTheClean) [inline src/twitch.py:155]: Should we print something helpful here? At least for the time being to make sure this solution is working at suppressing these exceptions?

File: src/twitch.py [hunk 3]
```diff
@@ -142,14 +145,17 @@ async def bgdailii(ctx):
...
-@twitchBot.command(name='wall_lii')
-async def wall_lii(ctx):
-    await ctx.send('HeyGuys I\'m a bot that checks the BG leaderboard to get data about player ranks and daily MMR fluctuations. I reset daily at Midnight CA time. Try using !bgrank [name] and !bgdaily [name] and !yesterday [name]. Also try !buddy [hero] and !goldenbuddy [hero] for buddy info')
-
-@twitchBot.command(name='help')
+@twitchBot.command(name='help', aliases=['wall_lii'])
 async def help(ctx):
     await ctx.send('HeyGuys I\'m a bot that checks the BG leaderboard to get data about player ranks and daily MMR fluctuations. I reset daily at Midnight CA time. Try using !bgrank [name] and !bgdaily [name] and !yesterday [name]. Also try !buddy [hero] and !goldenbuddy [hero] for buddy info')
 
+@twitchBot.event()
```
Comment (JimLiu0) [inline src/twitch.py:152]: Traceback (most recent call last):
  File "src/twitch.py", line 152, in <module>
    @twitchBot.event()
TypeError: event() missing 1 required positional argument: 'func'

File: src/twitch.py (hunk 1 above)
Comment (quinnabrvau) [reply src/twitch.py:156]: so these should be errors that have been caught, I believe this is matching the current handling of these errors

File: src/twitch.py (hunk 2 above)
Comment (quinnabrvau) [reply src/twitch.py:155]: isn't the goal to suppress these exceptions. CommandNotFound just means it's probably a command for another bot

File: src/twitch.py (hunk 3 above)
Comment (quinnabrvau) [reply src/twitch.py:152]: that's weird I took that from the documentation https://twitchio.readthedocs.io/en/latest/exts/commands.html#twitchio.ext.commands.Bot.event_error

Comment (JimLiu0) [reply src/twitch.py:152]: I version locked twitchio to 1.2.3 and the latest version is far ahead of that now so it might not be supported. I will try to update to the latest version and fix anything that is broken because of that and then implement that function.

File: src/twitch.py (hunk 1 above)
Comment (JimLiu0) [reply src/twitch.py:156]: For now until there's a desire to raise and handle exceptions

File: src/twitch.py (hunk 3 above)
Comment (quinnabrvau) [reply src/twitch.py:152]: oh yeah I was looking at 2.1.5, I can't even find the docs anymore for older versions

**Comment by JimLiu0** [comment]
I added this code to ignore CommandNotFound after updating twitchio to 2.3.0

`
@twitchBot.event()
async def event_command_error(error, data):
    if type(data) == CommandNotFound:
        return
    traceback.print_exception( type(error), error, error.__traceback__, file=sys.stderr)
`

**Comment by JimLiu0** [comment]
Never mind this doesn't actually prevent these errors from still printing. It just allows for extra code to be ran.

Ignoring exception in command: No command "test" was found.:
twitchio.ext.commands.errors.CommandNotFound: No command "test" was found.
